spring:
  profiles:
    active: dev #激活开发环境配置
---
server:
  port: 8001 #端口号
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: edu.ft.bean
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
spring: 
  profiles: dev  #开发环境
  application:
    name: ms-product-new
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3307/springcloud_db02?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: 123456
     dbcp2:
       min-idle: 5                                # 数据库连接池的最小维持连接数
       initial-size: 5                            # 初始化连接数
       max-total: 5                               # 最大连接数
       max-wait-millis: 150                       # 等待连接获取的最大超时时间
# Eureka客户端注册配置
eureka:
  client:
    register-with-eureka: true # 开启服务注册
    fetch-registry: true       # 开启服务发现
    service-url:
      # 单个微服务注册中心的服务地址
      #      defaultZone: http://localhost:6001/eureka
      # 集群注册，需要注册到所有的集群机器中（多个地址用逗号隔开）
      defaultZone: http://eureka6001.com:6001/eureka
    instance:
    #修改微服务注册中心显示的status值
    instance-id: ${spring.application.name}:${server.port}
    #在status点击url路径前加上ip地址
    prefer-ip-address: true
#自定义配置属性
student:
  name: wangwu
---
server:
  port: 8001 #端口号
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: edu.ft.bean
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
spring: 
  profiles: prod #开发环境
  application:
    name: ms-product
    datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://127.0.0.1:3307/springcloud_db02?serverTimezone=GMT%2B8  # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间
# Eureka客户端注册配置
eureka:
  client:
    register-with-eureka: true # 开启服务注册
    fetch-registry: true       # 开启服务发现
    service-url:
      # 单个微服务注册中心的服务地址
      #      defaultZone: http://localhost:6001/eureka
      # 集群注册，需要注册到所有的集群机器中（多个地址用逗号隔开）
      defaultZone: http://eureka6001.com:6001/eureka
    instance:
    #修改微服务注册中心显示的status值
    instance-id: ${spring.application.name}:${server.port}
    #在status点击url路径前加上ip地址
    prefer-ip-address: true
